name: 'Google Chat Action'
author: 'D Ther Htun'
description: 'Github actions for google chat Room Bot'
branding:
  icon: 'at-sign'
  color: 'green'
inputs:
  project: 
    description: 'Github Project Name'
    required: true
  commit:
    description: 'Github Commit ID'
    required: true
  branch:
    description: 'Github Branch'
    required: true
  status:
    description: 'Github Action Build Status'
    required: true
  actionid:
    description: 'Current Running Action ID'
    required: true
  webhook:
    description: 'Google Chat Webhook URL'
    required: true

runs:
  using: 'docker'
  image: 'docker://dimasd/google-chat-action'
  args:
    - ${{ inputs.project }}
    - ${{ inputs.commit }}
    - ${{ inputs.branch }}
    - ${{ inputs.status }}
    - ${{ inputs.actionid }}
    - ${{ inputs.webhook }}
